name: Deploy
on:
  push:
    branches: main
    paths:
      - '.github/workflows/deploy.yml'
      - 'package.json'
      - 'package-lock.json'
      - 'wrangler.toml'
jobs:
  publish:
    name: Deploying workaholic worker to Cloudlfare
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.OS }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-npm-
            ${{ runner.OS }}-
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: Build worker
        run : npx workaholic build worker.js --minify
      - name: Deploy worker
        run: npx wrangler publish
        env:
          CF_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
